--- #YAML:1.0
name:               Statistics-R
version:            0.09
abstract:           Controls the R interpreter through Perl.
author:
    - Graciliano M. P. <gm@virtuasites.com.br>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Regexp::Common:  0
    Test::More:      0.47
    Text::Balanced:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
